### ISSUE TITLE
Problem with adding/depositing in testnet.

### ISSUE THREAD

**Issue by sseibetsu** [vividnetwork/aptoswap#1]
I've got problem with adding/depositing in testnet: I've claimed tokens from "Token", then I've moved to "Pool & Position", and tried to add pool but there was mistake:
![image](https://user-images.githubusercontent.com/76789420/197587584-f13c69ae-4cf9-4d4c-8c3a-19e156757521.png)

Here you can see, that I have tokens to add pool:
![image](https://user-images.githubusercontent.com/76789420/197587685-c2dec1ec-e57a-496c-96b3-e59be913754c.png)

I'm not the only one who facing this problem. There a lot of people with this mistake.
I really hope that you will handle with all problems and make everything good)

**Comment by anarasam** [comment]
Not Found - Request ID: 01GGC8W92CSNFF1EA1T7X794RN

**Comment by anarasam** [comment]
Not Found - Request ID: 01GGC9703QH55RN4385D3AW8RW

**Comment by anarasam** [comment]
Not Found - Request ID: 01GGC9703QH55RN4385D3AW8RW
Not Found - Request ID: 01GGC9703QH55RN4385D3AW8R
0x36c8...b6f4
0x36c82c31579bfe1a78816c45c44b1416e4ddbdf94572103818319d024c9ab6f4

**Comment by anarasam** [comment]
Not Found - Request ID: 01GGC9DD1TA0S3MKSWB8SEEEAZ

**Comment by anarasam** [comment]
Not Found - Request ID: 01GGC9EMG1CX5Z2BAGZM2CRC8D

**Comment by anarasam** [comment]
Not Found - Request ID: 01GGC9H5JCXWW789HVAGFRH24H

**Comment by vividgithub** [comment]
No code
